name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TeX Live with xelatex and full fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-latex-recommended texlive-latex-extra

      - name: Compile PDF from sato.tex
        run: xelatex -interaction=nonstopmode sato.tex || true

      - name: Create index.html with license and warning
        run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<html><head><meta charset="UTF-8"><title>Sato - PDF Output</title>' >> index.html
          echo '<style>' >> index.html
          echo 'body { margin: 0; font-family: sans-serif; }' >> index.html
          echo '.warning { background-color: #ffcc00; color: #000; font-weight: bold; font-size: 1.5em; padding: 1em; text-align: center; border-bottom: 2px solid #000; }' >> index.html
          echo '.footer { font-size: 0.9em; text-align: center; padding: 10px; color: #444; background: #f9f9f9; border-bottom: 1px solid #ccc; }' >> index.html
          echo '</style></head><body>' >> index.html
          echo '<div class="footer">' >> index.html
          echo 'PDF licensed under <a href="https://creativecommons.org/licenses/by-nd/4.0/">CC BY-ND 4.0</a>.' >> index.html
          echo ' Source code licensed under <a href="https://www.gnu.org/licenses/gpl-3.0.html">GPLv3+</a>.' >> index.html
          echo ' View source on <a href="https://github.com/ngutlhtej/sato">GitHub</a>.' >> index.html
          echo '</div>' >> index.html
          echo '<div class="warning">WORK IN PROGRESS - NOT A REFERENCE DOCUMENT</div>' >> index.html
          echo '<embed src="sato.pdf" type="application/pdf" width="100%" height="1000px"/>' >> index.html
          echo '<div class="footer">' >> index.html
          echo 'PDF licensed under <a href="https://creativecommons.org/licenses/by-nd/4.0/">CC BY-ND 4.0</a>.' >> index.html
          echo ' Source code licensed under <a href="https://www.gnu.org/licenses/gpl-3.0.html">GPLv3+</a>.' >> index.html
          echo ' View source on <a href="https://github.com/ngutlhtej/sato">GitHub</a>.' >> index.html
          echo '</div></body></html>' >> index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

